### ISSUE TITLE
Buf1 or Buf2 Wrong Folder

### ISSUE THREAD

**Issue by westrajos** [nolenroyalty/flappy-dird#10]
One of the "Bufs" is ordering folders incorrectly, causing the pipe to move up and down and the bird to split. On Buf1 the pipes float and the bird splits in half. I use the latest version of MacOS Monterey.

![Screen Shot 2024-11-06 at 12 53 23 PM](https://github.com/user-attachments/assets/5a6d4c6e-6de3-47d4-baaa-7553d6dbe605).

**Comment by nolenroyalty** [comment]
Hi! You need to navigate into both `buf1` and `buf2` and sort the folders by "Date Modified" - see the README

**Comment by westrajos** [comment]
The folders are sorted by "Date Modified", maybe I could try setting it up again? ![Screen Shot 2024-11-06 at 1 53 32 PM](https://github.com/user-attachments/assets/18851cc9-fe98-4449-9bf1-5aab10d8c910)

**Comment by nolenroyalty** [comment]
Are you sure they're sorted by Date Modified right now? The little "Up" chevron (to the left of Date Modified) makes me think that they're sorted by the first column instead. When I sort by Date Modified the chevron appears to the right of the "Date Modified" text.

I don't know what "Today" means in the first column - I see "Name" there instead. So maybe you have a different finder setup.

**Comment by westrajos** [comment]
YES YES YES YES! IT WORKS!

**Comment by westrajos** [comment]
"Date Modified" is to the right of the folders in "Buf1" and "Buf2". You must have the carrot facing upwards, (the carrot is hidden until you click the "Date Modified" carrot.
