### ISSUE TITLE
Unplayable on macOS Sonoma 14.0 (23A344)

### ISSUE THREAD

**Issue by itspluxstahre** [nolenroyalty/flappy-dird#2]
In Sonoma, the bird will stay at the top row and never fall down even if not flapping. 
Which makes it pretty unplayable. 

![CleanShot 2023-10-09 at 02 12 17@2x](https://github.com/nolenroyalty/flappy-dird/assets/99403/005a3a35-c26f-49ae-bb22-5edafa38ec7e)

**Comment by nolenroyalty** [comment]
Oh! Can you sort your finder directories by last modified instead of name?
forgot to add that to instructions.

on mobile but will fix tonight.

**Comment by nolenroyalty** [comment]
@itspluxstahre I've updated the instructions, can you confirm that the game works for you now?

**Comment by itspluxstahre** [comment]
Ah that made a lot of sense now when I understood how the folders needed to be sorted and it works! Thx!
